# Generated by Django 5.0.3 on 2024-04-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('resolution', models.CharField(max_length=30)),
                ('trained_model', models.CharField(choices=[('YOLO', 'YOLO'), ('RCNN', 'RCNN'), ('SSD', 'SSD')], max_length=10)),
                ('fps', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('gate_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('status', models.CharField(choices=[('CLOSED', 'CLOSED'), ('OPEN', 'OPEN')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GateCamera',
            fields=[
                ('gate_camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gates_cameras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityOfficersGate',
            fields=[
                ('security_officers_gate_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_shift', models.CharField(choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'security_officers_gate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('SECURITY_OFFICER', 'SECURITY_OFFICER')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_roles',
                'managed': False,
            },
        ),
    ]
