# Generated by Django 5.0.3 on 2024-03-28 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('resolution', models.CharField(max_length=30)),
                ('trained_model', models.CharField(choices=[('YOLO', 'YOLO'), ('RCNN', 'RCNN'), ('SSD', 'SSD')], max_length=10)),
                ('fps', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('gate_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('status', models.CharField(choices=[('CLOSED', 'CLOSED'), ('OPEN', 'OPEN')], max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityOfficer',
            fields=[
                ('security_officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GateCamera',
            fields=[
                ('gate_camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camera')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gate')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityOfficersGate',
            fields=[
                ('security_officers_gate_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_shift', models.CharField(choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], max_length=5)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gate')),
                ('security_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.securityofficer')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('SECURITY_OFFICER', 'SECURITY_OFFICER')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
