# Generated by Django 5.0.3 on 2024-03-29 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gatecamera_created_at_gatecamera_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
